allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  core-js-pure: true
  esbuild: false
  maplibre-gl: false
  sharp: true
  ttf2woff2: false
  unrs-resolver: false
  vue-demi: false
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/workers-types'
  - '@eslint/plugin-kit'
  - '@iconify-json/lucide'
  - '@vue/language-core'
  - eslint
  - vue-tsc
  - '@nuxt/eslint-config@1.16.0'
  - '@nuxt/eslint-plugin@1.16.0'
  - '@nuxt/eslint@1.16.0'
