allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  esbuild: false
  sharp: true
  ttf2woff2: false
  unrs-resolver: false
  vue-demi: false
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@4.20260528.1'
  - '@eslint/plugin-kit@0.7.2'
  - '@iconify-json/lucide@1.2.111'
  - '@vue/language-core@3.3.3'
  - eslint@10.4.1
  - vue-tsc@3.3.3
