export type InboxMessageSource = 'CONTACT_FORM' | 'EMAIL'
export type InboxMessageStatus = 'NEW' | 'OPEN' | 'REPLIED' | 'ARCHIVED' | 'SPAM'
export type InboxMessageKind = 'LEAD' | 'COLLABORATION' | 'PERSONAL' | 'SUPPORT' | 'OTHER' | 'SPAM'
export type InboxMessagePriority = 'LOW' | 'NORMAL' | 'HIGH'
export type InboxReplyStatus = 'DRAFT' | 'QUEUED' | 'SENT' | 'FAILED'
