query LeadsWorkspace($input: LeadsWorkspaceInput) {
  leadsWorkspace(input: $input) {
    summary {
      total
      new
      qualified
      followUp
      won
      lost
      archived
    }

    leads {
      ...LeadItemFields
    }

    selectedLead {
      ...LeadItemFields
    }
  }
}
