query LeadWorkspace($input: LeadWorkspaceInput) {
  leadWorkspace(input: $input) {
    summary {
      total
      new
      qualified
      highPriority
      archived
    }

    leads {
      ...LeadItemFields
    }

    selectedLead {
      ...LeadItemFields
    }
  }
}
